spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 1234
    url: jdbc:postgresql://postgres-academia:5432/academia
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always